# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "⬆️ "

  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react-dnd"
      - dependency-name: "execa"
      - dependency-name: "rc-field-form"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "⬆️ "
