# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file 

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "⬆️ "

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    commit-message:
      prefix: "⬆️ "
    ignore:
        - dependency-name: "*"
          update-types: ["version-update:semver-patch"]
