version: '2'
checks:
    method-lines:
        config:
            threshold: 100
exclude_patterns:
    - 'src/**/*.stories.{js,jsx,mjs,ts,tsx}'
plugins:
    eslint:
        enabled: true
            config:
                config: .eslintrc
    stylelint:
        enabled: true