#https://octo.github.com/projects/repo-visualization

name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: ".github/diagram.yml"
          excluded_paths: ".github,.husky,.storybook,.vs,.vscode"
