name: Pull Request Build & Test

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run pre-commit-lint
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test
